energy <- read.csv("energy.csv", header=FALSE)
kinetic <- read.csv("kinetic.csv", header=FALSE)
poten <- read.csv("poten.csv", header=FALSE)
temp <- read.csv("temp.csv", header=FALSE)
vel <- read.csv("velocity.csv", header=FALSE)

png('energy.png')
plot(energy$V2, energy$V1, type="l", main=abs(max(abs(energy$V1-mean(energy$V1)))/mean(energy$V1)))
abline(a=mean(energy$V1),b=0)
dev.off()

png('temp.png')
#plot(temp$V2, temp$V1, type="l", main=abs(max(abs(temp$V1-mean(temp$V1)))/mean(temp$V1)))
plot(temp$V2[100:nrow(temp)], temp$V1[100:nrow(temp)], type="l", main=mean(temp$V1[100:nrow(temp)]), xlab=max(abs(temp$V1[100:nrow(temp)]-mean(temp$V1[100:nrow(temp)])))/mean(temp$V1[100:nrow(temp)]))
abline(a=mean(temp$V1[100:nrow(temp)]),b=0, col="red")
dev.off()

png('kinetic.png')
plot(kinetic$V2, kinetic$V1, type="l", main=abs(max(abs(kinetic$V1-mean(kinetic$V1)))/mean(kinetic$V1)))
abline(a=mean(kinetic$V1),b=0)
dev.off()

png('poten.png')
plot(poten$V2, poten$V1, type="l", main=abs(max(abs(poten$V1-mean(poten$V1)))/mean(poten$V1)))
abline(a=mean(poten$V1),b=0)
dev.off()

png('compare.png')
plot(energy$V2, energy$V1, type="l", xlab="", ylab="", ylim=range(c(energy$V1,kinetic$V1,poten$V1)))
par(new=TRUE)
plot(kinetic$V2, kinetic$V1, type="l", xlab="", ylab="", axes=FALSE, ylim=range(c(energy$V1,kinetic$V1,poten$V1)))
par(new=TRUE)
plot(poten$V2, poten$V1, type="l", xlab="", ylab="", axes=FALSE, ylim=range(c(energy$V1,kinetic$V1,poten$V1)))
dev.off()

png('vel.png')
hist(vel$V1, breaks=10)
dev.off()