energy <- read.csv("energy.csv", header=FALSE)
kinetic <- read.csv("kinetic.csv", header=FALSE)
poten <- read.csv("poten.csv", header=FALSE)
temp <- read.csv("temp.csv", header=FALSE)
vel <- read.csv("velocity.csv", header=FALSE)

png('energy.png')
plot(energy$V2, energy$V1, type="l", main=abs(max(abs(energy$V1-mean(energy$V1)))/mean(energy$V1)))
abline(a=mean(energy$V1),b=0)
dev.off()

png('temp.png')
#plot(temp$V2, temp$V1, type="l", main=abs(max(abs(temp$V1-mean(temp$V1)))/mean(temp$V1)))
step <- 0
plot(temp$V2[step:nrow(temp)], temp$V1[step:nrow(temp)], type="l", main=mean(temp$V1[step:nrow(temp)]), xlab=max(abs(temp$V1[step:nrow(temp)]-mean(temp$V1[step:nrow(temp)])))/mean(temp$V1[step:nrow(temp)]))
abline(a=mean(temp$V1[step:nrow(temp)]),b=0, col="red")
dev.off()

png('temp2.png')
step <- 5000
plot(temp$V2[step:nrow(temp)], temp$V1[step:nrow(temp)], type="l", main=mean(temp$V1[step:nrow(temp)]), xlab=max(abs(temp$V1[step:nrow(temp)]-mean(temp$V1[step:nrow(temp)])))/mean(temp$V1[step:nrow(temp)]))
abline(a=mean(temp$V1[step:nrow(temp)]),b=0, col="red")
dev.off()

png('kinetic.png')
plot(kinetic$V2, kinetic$V1, type="l", main=abs(max(abs(kinetic$V1-mean(kinetic$V1)))/mean(kinetic$V1)))
abline(a=mean(kinetic$V1),b=0)
dev.off()

png('poten.png')
plot(poten$V2, poten$V1, type="l", main=abs(max(abs(poten$V1-mean(poten$V1)))/mean(poten$V1)))
abline(a=mean(poten$V1),b=0)
dev.off()

png('compare.png')
plot(energy$V2, energy$V1, type="l", xlab="", ylab="", ylim=range(c(energy$V1,kinetic$V1,poten$V1)))
par(new=TRUE)
plot(kinetic$V2, kinetic$V1, type="l", xlab="", ylab="", axes=FALSE, ylim=range(c(energy$V1,kinetic$V1,poten$V1)))
par(new=TRUE)
plot(poten$V2, poten$V1, type="l", xlab="", ylab="", axes=FALSE, ylim=range(c(energy$V1,kinetic$V1,poten$V1)))
dev.off()

png('vel.png')
Temp <- mean(temp$V1[(nrow(temp)/2):nrow(temp)])
Max <- max(vel$V1)
curve(((1/(2*Temp*pi))^(3/2))*4*pi*(x^2)*exp(-(x^2)/(2*Temp)), 0, Max, ylab='', yaxt='n', col='red')
axis(1, col='red', col.axis='red')
par(new=TRUE)
hist(vel$V1)
dev.off()
