energy <- read.csv("energy.csv", header=FALSE)
temp <- read.csv("temp.csv", header=FALSE)
png('energy.png')
plot(energy$V2, energy$V1, type="l", main=abs(max(abs(energy$V1-mean(energy$V1)))/mean(energy$V1)))
abline(a=mean(energy$V1),b=0)
dev.off()
png('temp.png')
plot(temp$V2, temp$V1, type="l", main=abs(max(abs(temp$V1-mean(temp$V1)))/mean(temp$V1)))
abline(a=mean(temp$V1),b=0)
dev.off()